### ISSUE TITLE
Not works together with newest Better Questing Mod Beta

### ISSUE THREAD

**Issue by Dream-Master** [BrassGoggledCoders/BloodyQuests#1]
Not works together with newest Better Questing Mod Beta and MC 1.7.10

https://gist.github.com/Dream-Master/ff1bf48161dde7fa9dad9a921e142378

Mocpack

https://github.com/GTNewHorizons/NewHorizons

**Comment by NNM42** [comment]
plz add new BQ_api 2.0 compatibility for 1.7.x mod.

**Comment by FreneticScribbler** [comment]
Port is done but its refusing to compile. Working on it.

**Comment by Dream-Master** [comment]
Thanks

**Comment by NNM42** [comment]
Respect!
