### ISSUE TITLE
BQ Update

### ISSUE THREAD

**Issue by spannerman79** [BrassGoggledCoders/BloodyQuests#3]
https://minecraft.curseforge.com/projects/better-questing-standard-expansion/files/2694075
`NOTE: Sorry 3rd party expansion devs who may have to resurrect ancient versions of their mods`

**Comment by SkySom** [comment]
More like "Sorry we don't support 1.7.10 anymore, and it was silly of Funway to do this"

**Comment by FreneticScribbler** [comment]
Dammit Funway
